export const AGREGAR_A_POKEBD = "AGREGAR_A_POKEBD";
export const AGREGAR_A_POKEIZQ = "AGREGAR_A_POKEIZQ";
export const AGREGAR_A_POKEDER = "AGREGAR_A_POKEDER";
export const REINICIAR_POKEBD = "REINICIAR_POKEBD";
