export const AGREGAR_A_POKEIZQ = "AGREGAR_A_POKEIZQ";
export const AGREGAR_A_POKEDER = "AGREGAR_A_POKEDER";
export const BOOL_DATA = "BOOL_DATA";


export const LLENAR_ID_POKEMONES = "LLENAR_ID_POKEMONES";
export const SACAR_ID_POKEMON = "SACAR_ID_POKEMON";

export const AUMENTAR_PUNTOS = "AUMENTAR_PUNTOS";
export const REINICIAR_PUNTOS = "REINICIAR_PUNTOS";
